version: "2.2"
services:
  mongo:
    image: mongo
    restart: always
  userapp:
    build: .
    ports:
      - 9596:9596
    environment:
      - MONGODB_URL=mongodb://mongo:27017
    depends_on:
      - mongo
